# =====================================================
# CONFIGURACI\u00d3N DE LA API SIGTAL
# GA7-220501096-AA5-EV01
# =====================================================

spring.application.name=sigtal-api-aa5-ev01

# Puerto del servidor
server.port=8080

# =====================================================
# CONEXI\u00d3N A LA BASE DE DATOS SIGTAL
# =====================================================

spring.datasource.url=jdbc:mysql://localhost:3306/sigtal?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true